// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfIBS2gB4lkRZ1_ZerLk451EVfafrfWSM',
    appId: '1:491056452067:web:0c8ef019a651cd47c290d6',
    messagingSenderId: '491056452067',
    projectId: 'qtratamal',
    authDomain: 'qtratamal.firebaseapp.com',
    databaseURL: 'https://qtratamal-default-rtdb.firebaseio.com',
    storageBucket: 'qtratamal.firebasestorage.app',
    measurementId: 'G-8XF1WL9TDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKHjLtxd3KyTyFpWPVC03cpRYS10yQXTs',
    appId: '1:491056452067:android:3640f5b660b77808c290d6',
    messagingSenderId: '491056452067',
    projectId: 'qtratamal',
    databaseURL: 'https://qtratamal-default-rtdb.firebaseio.com',
    storageBucket: 'qtratamal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoxmMXgLO3jbdmgdh2t3LdDimVBYP-tdo',
    appId: '1:491056452067:ios:fcca1f7869debcf7c290d6',
    messagingSenderId: '491056452067',
    projectId: 'qtratamal',
    databaseURL: 'https://qtratamal-default-rtdb.firebaseio.com',
    storageBucket: 'qtratamal.firebasestorage.app',
    iosBundleId: 'com.example.bloodBank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoxmMXgLO3jbdmgdh2t3LdDimVBYP-tdo',
    appId: '1:491056452067:ios:fcca1f7869debcf7c290d6',
    messagingSenderId: '491056452067',
    projectId: 'qtratamal',
    databaseURL: 'https://qtratamal-default-rtdb.firebaseio.com',
    storageBucket: 'qtratamal.firebasestorage.app',
    iosBundleId: 'com.example.bloodBank',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfIBS2gB4lkRZ1_ZerLk451EVfafrfWSM',
    appId: '1:491056452067:web:94b4cafc408efdffc290d6',
    messagingSenderId: '491056452067',
    projectId: 'qtratamal',
    authDomain: 'qtratamal.firebaseapp.com',
    databaseURL: 'https://qtratamal-default-rtdb.firebaseio.com',
    storageBucket: 'qtratamal.firebasestorage.app',
    measurementId: 'G-4LK34DTV15',
  );
}
